### PR TITLE
Decio fixes

### PR DESCRIPTION
**Pull request by deciob**
Fixes:
[71031690](https://www.pivotaltracker.com/story/show/71031690)
[68204378](https://www.pivotaltracker.com/story/show/68204378)
[67464164](https://www.pivotaltracker.com/story/show/67464164)
[70954206](https://www.pivotaltracker.com/s/projects/1035726/stories/70954206)

Possibly it needs the creation of a "./log/cron.log" on production? As this is not checked into git.

### CODE REVIEW

**Comment by deciob** [comment]
:)

**Comment by simaob** [comment]
It was about time! :dancer:

**Comment by deciob** [comment]
Was just thinking the same!

**Comment by agnessa** [comment]
sorry guys, I'm quite meticulous about code reviews!

**Comment by deciob** [comment]
fair enough

**Comment by simaob** [comment]
You are the pro, so I trust your judgement. =)
I hope you guys are doing well!

**Comment by deciob** [comment]
All is great Simao! Thanks! And you?

**Pull request merged**
